version: '2'
services:
  nginx:
    image: nginx
    links:
      - ckan
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
  ckan:
    image: codefordc2/cfdc-ckan:latest
    restart: on-failure
    volumes: 
      - ./ckanext:/usr/lib/ckan/default/ckanext-open_data_dc/ckanext
      - ./etc/production:/etc/ckan/default
    ports:
      - "5000:5000"
    links:
      - solr
      - redis
    environment:
      - DB_PORT_5432_TCP_ADDR=${DB_URL_PROD_BACK}
      - DB_PORT_5432_TCP_PORT=5432
      - SOLR_PORT_8983_TCP_ADDR=solr
      - REDIS_PORT_6379_TCP_ADDR=redis
      - REDIS_PORT_6379_TCP_PORT=6379
      - SOLR_PORT_8983_TCP_PORT=8983
      - CKAN_CONFIG=/etc/ckan/default
      - DB_ENV_POSTGRES_USER=ckan_default
      - DB_ENV_POSTGRES_PASSWORD=codefordc_ckan
      - CKAN_SITE_URL=http://nginx
  solr:
    image: codefordc2/ckan-solr
    ports:
      - "8983:8983"
  redis:
    image: redis:latest
  datapusher:
    image: easyckan/ckan-datapusher:2.6
    restart: on-failure
    links:
      - nginx
      - ckan
    ports:
      - "8800:8800"

